[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Disable secrets scanning for public configuration values
  SECRETS_SCAN_OMIT_KEYS = "VITE_APP_TITLE,VITE_APP_DESCRIPTION,VITE_APP_URL,VITE_CONTACT_EMAIL,VITE_CONTACT_PHONE,VITE_GITHUB_URL,VITE_LINKEDIN_URL,VITE_INSTAGRAM_URL,VITE_GITHUB_OWNER,VITE_GITHUB_REPO,VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_APP_ID,VITE_FIREBASE_MEASUREMENT_ID"

# Redirect rules
[[redirects]]
  from = "/admin"
  to = "/admin"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200