[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Disable secrets scanning entirely for this public portfolio
  SECRETS_SCAN_ENABLED = "false"

# Redirect rules
[[redirects]]
  from = "/admin"
  to = "/admin"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200